import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Banner from "../components/Banner/Banner";
import axios from "axios";
import { menuType } from "../interface";
import { client } from "../../lib/sanity";
import Featured from "../components/Featured/Featured";
import Link from "next/link";
import Locations from "../components/Locations/Locations";

const Home: NextPage = ({
  featuredMenuData,
  locationData,
  galleryData
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  console.log(galleryData);
  return (
    <section>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Featured data={featuredMenuData} />
      <div className="flex mt-8 justify-center">
        <Link href="/menu">
          <button className="bg-button-pink transition-all duration-300 hover:bg-red-500  rounded-lg text-white text-14 font-lemonada p-2">
            View full menu
          </button>
        </Link>
      </div>
      <Locations data={locationData} />
    </section>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  const menus = await axios.get(`${process.env.API_URL}/api/menu`);
  const locations = await axios.get(`${process.env.API_URL}/api/location`);
  const featuredMenu = menus.data.filter(
    (item: menuType) => item.featured === true
  );
  const query=  '*[_type == "gallery"]';
  const galleries = await client.fetch(query);

  const res = await Promise.all([featuredMenu, locations]);
  return {
    props: {
      featuredMenuData: res[0],
      locationData: res[1].data,
      galleryData: galleries
    },
  };
};

export default Home;
